name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: install pnpm
        run: npm i pnpm@latest -g

      - name: Install dependencies
        run: pnpm install

      - name: Run CI
        run: pnpm run ci
